<?xml version="1.0" encoding="utf-8"?><Database Name="QLHocSinh" Class="QLHocSinhDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-HTON42J2\SQLEXPRESS;Initial Catalog=QLHocSinh;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="ProjectQLHS.Properties.Settings" SettingsPropertyName="QLHocSinhConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HocSinh" Member="HocSinhs">
    <Type Name="HocSinh">
      <Column Name="MaHS" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoHS" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TenHS" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="HocSinh_TaiKhoan" Member="TaiKhoan" ThisKey="MaHS" OtherKey="Username" Type="TaiKhoan" Cardinality="One" />
      <Association Name="Lop_HocSinh" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="MaLop" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SiSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GVCN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Lop_HocSinh" Member="HocSinhs" ThisKey="MaLop" OtherKey="MaLop" Type="HocSinh" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="Username" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="HocSinh_TaiKhoan" Member="HocSinh" ThisKey="Username" OtherKey="MaHS" Type="HocSinh" IsForeignKey="true" />
    </Type>
  </Table>
</Database>